// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search" | "/account" | "/login" | "/signup";
  };
  "./components/globalTheme/globalShell.tsx": {
    id: "components/globalTheme/globalShell";
    page: "/" | "/search" | "/account";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/Search.tsx": {
    id: "pages/Search";
    page: "/search";
  };
  "./components/dashboard/Dashboard.tsx": {
    id: "components/dashboard/Dashboard";
    page: "/account";
  };
  "./pages/Account.tsx": {
    id: "pages/Account";
    page: "/account";
  };
  "./components/auth/AuthLayout.tsx": {
    id: "components/auth/AuthLayout";
    page: "/login" | "/signup";
  };
  "./pages/Login.tsx": {
    id: "pages/Login";
    page: "/login";
  };
  "./pages/Signup.tsx": {
    id: "pages/Signup";
    page: "/signup";
  };
};